### ISSUE TITLE
Choose a meaningful name for the repo + pkg

### ISSUE THREAD

**Issue by rfay** [drud/go-pantheon#1]
Both the repo and the package name are 'elysium', which doesn't mean anything to me at least. Maybe elysian fields? I'd say just go with go-terminus or something like that.  "Elysian Fields: in the realm of Hades, where mortals related to the gods, the heroic and the virtuous, could rest in a blessed and happy life after death"

**Comment by beeradb** [comment]
I got unofficial word last night from Josh at Pantheon. "I would not worry about trademark 😛 ". 

I'm comfortable enough with that to move forward w/ a rename that includes pantheon. I'd suggest `go-pantheon` as a repo name as `pantheon` as a package name.

As a part of this rename, I'll submit a PR which removes all references to elysium, and adds a nice disclaimer to the top of the readme which makes it clear this is not an official pantheon project.

**Comment by beeradb** [comment]
Opened a PR for this in https://github.com/drud/elysium/pull/6/files

**Comment by beeradb** [comment]
#6 was merged and the project was renamed. Merging this as such.
