### ISSUE TITLE
A new file structure in go-pantheon/pkg/pantheon

### ISSUE THREAD

**Issue by nmccrory** [drud/go-pantheon#10]
1. By splitting `session.go` into `client.go` and `auth.go` we separate concerns for our HTTP helpers and session authentication.
2. The `setup()` and `teardown()` testing methods that we use will be in their own file and globally available to all other test files in the package.
3. Loose coupling of client services and auth services makes session initialization more clean, syntactically, for consumers of the library.

The test for httpRequest is extremely cumbersome to write. This is because you must pass a type that implements the RequestEntity interface. Extremely similar to or even repeated lines of code are being used in any object that makes requests.

We can consolidate the useful pieces of RequestEntity into a global HTTP management file. Then it becomes way easier for developers to create an infinite number of services all built on the foundation of an authenticated Pantheon API Token. 

The HTTP management file handles encode/decode of JSON and API call execution for all services. There is really no need to make everyone implement an interface, in my opinion.

Using the proposed method, example API calls would look like this:
```go
// Initialize an instance of the go-pantheon client 
client := pantheon.NewClient()
// Set a path for saving state to disk (optional).
client.Path("/home/user/.go-pantheon/savedsession")
// "Login". Authenticate with a token.
user, resp, err := client.Authenticate(os.Getenv("TERMINUS_API_TOKEN"))

// Save a user's session information to disk.
err := user.Save()
// Read a user's previous session from disk.
err := user.Load()

// Get a list of a user's sites.
sites, resp, err := user.Sites().SiteList()
// Get a list of environments for a given site.
site := sites[0]
environments := site.EnvironmentList()
```

**Comment by rfay** [comment]
Closing this for now, since this is not an active project, pretty much just in maintenance mode.
