### ISSUE TITLE
Missing test for `go-pantheon/pkg/pantheon/request.go`

### ISSUE THREAD

**Issue by nmccrory** [drud/go-pantheon#9]
## What happened (or feature request):
There is currently no test for the `httpRequest()` function in `request.go`.

## What you expected to happen:
I expected there to be a test that creates a new HTTP request using the `httpRequest()` helper.

## Some benefits: 
- We verify that all HTTP headers are being properly set by its default setter function (which also lives in `request.go`)
- And confirm that HTTP requests are being constructed and made successfully at a low level

**Comment by rfay** [comment]
Looking Oh-So-Forward to that PR!

**Comment by rickmanelius** [comment]
@nmccrory Given that your PS is merged, is there anything else remaining on this issue or can we consider it closed. Thanks!
